"""add created_at/updated_at to shopping_lists

Revision ID: 0baf0d5ae42a
Revises: 0ff37c5aee19
Create Date: 2026-07-12 16:19:47.641474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0baf0d5ae42a'
down_revision: Union[str, None] = '0ff37c5aee19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('shopping_lists', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_lists', 'updated_at')
    op.drop_column('shopping_lists', 'created_at')
    # ### end Alembic commands ###
