"""add_store_id_to_shopping_lists

Revision ID: 7f5b8d96f13f
Revises: c284b3292614
Create Date: 2026-07-12 23:09:04.015614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5b8d96f13f'
down_revision: Union[str, None] = 'c284b3292614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'shopping_lists', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_lists', type_='foreignkey')
    op.drop_column('shopping_lists', 'store_id')
    # ### end Alembic commands ###
