"""create_all_tables

Revision ID: ace5ef00cc7c
Revises: 
Create Date: 2026-07-12 15:47:34.783034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace5ef00cc7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_lists',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_registered_items',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('default_unit', sa.String(length=20), nullable=False),
    sa.Column('default_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_declarations',
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('pre_registered_item_id', sa.UUID(), nullable=False),
    sa.Column('declared_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calculated_need', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pre_registered_item_id'], ['pre_registered_items.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list_items',
    sa.Column('shopping_list_id', sa.UUID(), nullable=False),
    sa.Column('pre_registered_item_id', sa.UUID(), nullable=True),
    sa.Column('custom_name', sa.String(length=120), nullable=True),
    sa.Column('estimated_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pre_registered_item_id'], ['pre_registered_items.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('pre_registered_item_id', sa.UUID(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_price_cents', sa.Integer(), nullable=True),
    sa.Column('last_store_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['last_store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['pre_registered_item_id'], ['pre_registered_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pre_registered_item_id')
    )
    op.create_table('movements',
    sa.Column('sequential_code', sa.String(length=20), nullable=False),
    sa.Column('shopping_list_item_id', sa.UUID(), nullable=True),
    sa.Column('pre_registered_item_id', sa.UUID(), nullable=True),
    sa.Column('custom_name', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('store_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pre_registered_item_id'], ['pre_registered_items.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_item_id'], ['shopping_list_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movements')
    op.drop_table('stock')
    op.drop_table('shopping_list_items')
    op.drop_table('inventory_declarations')
    op.drop_table('pre_registered_items')
    op.drop_table('stores')
    op.drop_table('shopping_lists')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
